language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit --configuration phpunit.xml --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

allow_failures:
  - php: nightly