language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit --configuration phpunit.xml

allow_failures:
  - php: nightly