language: php

php:
  - 7.1
  - 7.2
  - nightly

services:
    - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS flytest;'

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

allow_failures:
  - php: nightly